name: flutter_urbacity
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  flutter:
    sdk: flutter
  go_router: ^12.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: NewTegomin
      fonts:
        - asset: assets/fonts/NewTegomin-Regular.ttf

    - family: CormorantGaramond
      fonts:
        - asset: assets/fonts/CormorantGaramond-Regular.ttf

    - family: MarkoOne-Regular
      fonts:
        - asset: assets/fonts/MarkoOne-Regular.ttf

    - family: JustMeAgainDownHere-Regular
      fonts:
        - asset: assets/fonts/JustMeAgainDownHere-Regular.ttf  

  assets:
    - assets/fotos/
